[workspace]
members = ["clippy", "clippy-gui", "clippy-server"]


[workspace.dependencies]
serde_json = "1.0.140"
serde = { version = "1.0", features = ["derive"] }
tokio = { version = "1", features = ["full"] }
