name: Release Linux

on:
  workflow_run:
    workflows: ["create release"]
    types:
      - completed

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: ""

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        BUILD_TARGET: [release]

    steps:
      - uses: actions/checkout@v4

      - name: Install build dependencies
        run: sudo apt-get update && sudo apt-get install -y build-essential pkg-config libssl-dev libxkbcommon-dev

      - name: Set up Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1

      - name: Build
        run: build-linux/build.sh

      - name: Upload Release Asset
        uses: softprops/action-gh-release@v1
        with:
          files: "build/clippy-*.tar.gz"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
